image: node:latest

stages:
  - build
  - deploy
  
before_script:
  - npm install


build_master:
  stage: build
  script:
  - npm run build
  only: ['master']


deploy_master:
  stage: deploy
  script:
    - echo "deploy Build"
  only: ['master']
